apps/food/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-21 下午5:22'

from django.conf.urls import url


from .views import FoodCreateView, FoodDetailView, FoodExploreView, FoodListView

urlpatterns = [
    # 食物推荐发表
    url(r'^foodcreate/$', FoodCreateView.as_view(), name='foodcreate'),

    # 食物详情
    url(r'^fooddetail/(?P<food_id>\d+)/$', FoodDetailView.as_view(), name='fooddetail'),

    # 发现食物
    url(r'^foodexplore/$', FoodExploreView.as_view(), name='foodexplore'),

    # 食物列表
    url(r'^foodlist/$', FoodListView.as_view(), name='foodlist'),
]

apps/topic/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-21 下午4:52'
from django.conf.urls import url

from .views import TopicListView, TopicDetailView, TopicCreateView

urlpatterns = [
    # 话题列表
    url(r'^topiclist/$', TopicListView.as_view(), name='topiclist'),

    # 话题详情
    url(r'^topicdetail/(?P<topic_id>\d+)/$', TopicDetailView.as_view(), name='topicdetail'),

    # 创建话题
    url(r'^topiccreate/$', TopicCreateView.as_view(), name='topiccreate'),
]

apps/user/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-19 上午10:25'
from django.conf.urls import url

from .views import LoginView, RegisterView, ActiveView, LogoutView, UserFollowingView, UserShareView
from .views import TopicCollectionView, UserIndexView, UserSettingView, UserHaveEatedView, UserFollowerView, UserWantEatView
from .views import FollowView, GetCityView

urlpatterns = [
    # 账户相关
    # 用户登录页面
    url(r'^login/$', LoginView.as_view(), name='login'),
    # 用户登出页面
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    # 用户注册页面
    url(r'^register/$', RegisterView.as_view(), name="register"),
    # 用户激活页面
    url(r'^active_user/(?P<active_code>.*)/$', ActiveView.as_view(), name="active_user"),


    #用户个人信息相关
    # 当前用户在关注谁
    url(r'^userfollowing/(?P<user_id>\d+)/$', UserFollowingView.as_view(), name="userfollowing"),
    # 当前用户的粉丝
    url(r'^userfollower/(?P<user_id>\d+)/$', UserFollowerView.as_view(), name="userfollower"),
    # 用户收藏的专题
    url(r'^topiccollection/(?P<user_id>\d+)/$', TopicCollectionView.as_view(), name='topiccollection'),
    # 用户首页
    url(r'^userindex/(?P<user_id>\d+)/$', UserIndexView.as_view(), name='userindex'),
    # 用户设置,包括用户的个人信息设置和用户的背景图片的设置
    url(r'^usersetting/(?P<user_id>\d+)/$', UserSettingView.as_view(), name='usersetting'),
    # 用户吃过的食物列表
    url(r'^usereated/(?P<user_id>\d+)/$', UserHaveEatedView.as_view(), name='usereated'),
    # 用户想吃的食物列表
    url(r'^userwanteat/(?P<user_id>\d+)/$', UserWantEatView.as_view(), name='userwanteat'),
    # 用户分享的列表
    url(r'^usershare/(?P<user_id>\d+)/$', UserShareView.as_view(), name='usershare'),


    # 用户行为相关
    # 用户关注的动作
    url(r'^follow/$', FollowView.as_view(), name='follow'),
    # 根据省份获取城市
    url(r'^get_cities/$', GetCityView.as_view(), name='get_cities'),
]

chihuoapp/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from user.views import IndexView

from chihuoapp.settings import MEDIA_ROOT


urlpatterns = [

    # 后台管理页面url
    url(r'^admin/', admin.site.urls),

    # 首页URL配置
    url('^$', IndexView.as_view(), name="index"),

    # 用户相关的url
    url(r'^user/', include('user.urls', namespace="user")),

    # 帖子
    url(r'^forum/', include('forum.urls', namespace="forum")),

    # 专题
    url(r'^topic/', include('topic.urls', namespace="topic")),

    # 食物
    url(r'^food/', include('food.urls', namespace="food")),

    # 验证码部分
    url(r'^captcha/', include('captcha.urls')),

    # 处理静态文件的函数配置
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

    # ] + static('static/', document_root=settings.STATIC_ROOT) + static('media/', document_root=settings.MEDIA_ROOT)

apps/user/models.py
from datetime import datetime

from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import AbstractUser

from location.models import City


# 用户信息数据表
class UserProfile(AbstractUser):
    nickname = models.CharField(max_length=16, verbose_name="昵称", default="")
    location = models.ForeignKey(City, null=True, blank=True, verbose_name='居住城市')
    introduction = models.TextField(max_length=1024, blank=True, null=True, verbose_name='个人简介')
    gender = models.CharField(max_length=8, choices=(("male", "先生"), ("female", "女士")), default="male", verbose_name="性别")
    birthday = models.DateTimeField(verbose_name="出生日期", null=True, blank=True)
    phone_num = models.CharField(max_length=11, verbose_name="手机号码", null=True, blank=True)
    image = models.ImageField(max_length=128, upload_to='media/user/image/%Y/%m/%d', verbose_name='头像',default="/media/image/superman.jpg")
    email = models.CharField(max_length=32, verbose_name="个人邮箱", default="")
    # userwantfood = models.ManyToManyField(Food, related_name="wantfood", verbose_name="用户想吃的食物", blank=True, symmetrical=False)
    # usercolltopic = models.ManyToManyField(FoodTopic, related_name="colltopic", verbose_name="用户收藏的专题", blank=True, symmetrical=False)
    total_wantnum = models.PositiveIntegerField(default=0, verbose_name="用户想吃的美食的总数")
    total_likenum = models.PositiveIntegerField(default=0, verbose_name="用户吃过的美食的总数")
    following = models.ManyToManyField('self', blank=True, related_name='followers', symmetrical=False, verbose_name="关注与被关注")

    def __str__(self):
        return self.username

    # def get_absolute_url(self):
    #     return reverse('user:userindex', kwargs={'user_id':self.id})

    class Meta:
        verbose_name = "用户信息"
        verbose_name_plural = verbose_name


# 使用邮箱注册以后，向注册邮箱发送验证码，验证用户的身份，完成用户的验证和激活
class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=16, verbose_name="验证码")
    email = models.CharField(max_length=32, verbose_name="邮箱")
    send_type = models.CharField(max_length=64, choices=(("register","注册"), ("forget_password","忘记密码"),("change_email","修改邮箱")), default="register", verbose_name="验证类型")
    send_time = models.DateTimeField(default=datetime.now, verbose_name="发送时间")

    def __str__(self):
        return '{0}({1})'.format(self.code,self.email)

    class Meta:
        verbose_name = "邮箱验证码"
        verbose_name_plural = verbose_name

apps/user/forms.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-19 上午10:49'

from django import forms
# from django.forms.extras.widgets import SelectDateWidget

from captcha.fields import CaptchaField

from .models import UserProfile


# 用户登陆的表单
class LoginForm(forms.Form):
    username = forms.CharField(required=True)
    password = forms.CharField(required=True, min_length=6)


# 用户注册的表单
class RegisterForm(forms.Form):
    username = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True, min_length=6)
    confirmPassword = forms.CharField(required=True, min_length=6)
    # captcha = CaptchaField()


# 用户修改个人信息的表单
class ModifyUserInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['image', 'gender', 'location', 'introduction']
        # widgets = {
        #     'birthday': forms.SelectDateWidget(years=range(1950,2017), attrs={'class':'selections'})
        # }

apps/user/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.generic.base import View
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.shortcuts import render_to_response
from django.contrib import messages

# from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from .models import UserProfile, EmailVerifyRecord
from .forms import LoginForm,RegisterForm, ModifyUserInfoForm
from utils.email_send import send_email
from utils.mixin_utils import LoginRequiredMixin
from topic.models import FoodTopic
from actions.models import Action
from actions.utils import create_action
from food.models import Food
from constants import *
from operation.models import UserWantEat, UserHaveAte, UserCollectTopic, UserLikeFood, UserDislikeFood, UserRecommendForum
from location.models import Province, City, Store


# 网站首页
class IndexView(View):
    def get(self, request):
        all_topics = FoodTopic.objects.all()
        # cur_user = request.user

        return render(request, "index.html", {
            'all_topics':all_topics,
            # 'user':cur_user,
        })


# 用户登录的时候账户名可以是用户名，可以是用户的邮箱
class CustomBackend(ModelBackend):
    def authenticate(self, username=None, password=None, **kwargs):
        try:
            user = UserProfile.objects.get(Q(username=username) | Q(email= username))
            if user.check_password(password):
                return user
        except Exception as e:
            return None


# 用户登录
class LoginView(View):
    def get(self, request):
        return render(request, "user/login.html", {})

    def post(self, request):
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            user_email = request.POST.get("username", "")
            pass_word = request.POST.get("password", "")
            user = authenticate(username = user_email, password = pass_word)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(reverse('index'))
                else:
                    return render(request, "user/login.html", {"msg": "用户未激活"})
            else:
                return render(request, "user/login.html", {"msg":"用户名或者密码错误"})
        else:
            return render(request, "user/login.html", { "login_form": login_form})


# 用户登出
class LogoutView(View):
    def get(self, request):
        logout(request)
        # request.user.is_authenticated = False
        return HttpResponseRedirect(reverse('index'))


# 用户注册
class RegisterView(View):
    def get(self, request):
        register_form = RegisterForm()
        return render(request, "user/register.html", {'register_form':register_form})
    def post(self, request):
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():
            user_name = request.POST.get("username", "")
            email = request.POST.get("email", "")
            password = request.POST.get("password", "")
            confirmPassword = request.POST.get("confirmPassword", "")
            if UserProfile.objects.filter(username = user_name):
                return render(request, "user/register.html", { "register_form": register_form, "msg": "用户已经存在" })
            elif UserProfile.objects.filter(email = email):
                return render(request, "user/register.html", { "register_form": register_form, "msg": "邮箱已经被注册" })
            elif password != confirmPassword:
                return render(request, "user/register.html", {"register_form": register_form, "msg": "两次输入的密码不一致"})
            else:
                user_profile = UserProfile()
                user_profile.username = user_name
                user_profile.email = email
                user_profile.is_active = False
                user_profile.password = make_password(password)
                user_profile.save()

                send_email(email, "register")
                return render(request, "user/active_successfully.html")
        else:
            return render(request, "user/register.html", {"register_form": register_form, "msg": "填入的信息有误" })


# 用户激活
class ActiveView(View):
    def get(self,request, active_code):
        all_records = EmailVerifyRecord.objects.filter(code=active_code)
        if all_records:
            for record in all_records:
                email = record.email
                user = UserProfile.objects.get(email = email)
                user.is_active = True
                user.save()
        else:
            return render(request, "user/active_fail.html")
        return HttpResponseRedirect(reverse('user:login'))


# 当前用户在关注谁
class UserFollowingView(View):
    def get(self, request, user_id):
        cur_user = UserProfile.objects.get(id=int(user_id))
        followings = cur_user.following.all()
        return render(request, "user/user_following.html", {
            'user':cur_user,
            'followings':followings,
        })


# 当前用户被谁关注
class UserFollowerView(View):
    def get(self, request, user_id):
        cur_user = UserProfile.objects.get(id=int(user_id))
        followers = cur_user.followers.all()
        return render(request, "user/user_follower.html", {
            'user':cur_user,
            'followers':followers,
        })


# 用户收藏的话题
class TopicCollectionView(View):
    def get(self, request, user_id):
        cur_user = UserProfile.objects.get(id=int(user_id))
        curuser_coll_topics = UserCollectTopic.objects.filter(user=cur_user)
        coll_topics_list = []
        for user_coll_topic in curuser_coll_topics:
            coll_topic = FoodTopic.objects.get(id=user_coll_topic.topic_id)
            coll_topics_list.append(coll_topic)
        return render(request, "user/topic_collection.html", {
            'user':cur_user,
            'collections':coll_topics_list,
        })


# 用户个人首页的部分
class UserIndexView(View):
    def get(self, request, user_id):
        cur_user = UserProfile.objects.get(id=int(user_id))
        recent_actions = Action.objects.filter(user=cur_user).all()[:10]
        return render(request, "user/user_index.html", {
            'user':cur_user,
            'actions':recent_actions,
        })


# 用户修改和人的信息
class UserSettingView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        provinces = Province.objects.all()
        for province in provinces:
            cities = province.city_set.all()
        cur_user = UserProfile.objects.get(id=int(user_id))
        form = ModifyUserInfoForm(instance=cur_user)
        return render(request, "user/user_setting.html", {
            'user':cur_user,
            'form':form,
            'provinces':provinces,
            'cities':cities,
        })

    def post(self, request, user_id):
        provinces = Province.objects.all()
        for province in provinces:
            cities = province.city_set.all()
        cur_user = UserProfile.objects.get(id=int(user_id))
        form = ModifyUserInfoForm(instance=cur_user, data=request.POST, files=request.FILES)
        if form.is_valid():
            print(form.cleaned_data)
            form.save()
            # form.save_m2m()
            messages.success(request, PROFILE_UPDATE_SUCCESS)
        else:
            messages.error(request, PROFILE_UPDATE_FAIL)
        return render(request, "user/user_setting.html", {
            'user':cur_user,
            'form':form,
            'provinces': provinces,
            'cities': cities,
        })




# 用户吃过的食物的列表
class UserHaveEatedView(View):
    def get(self, request, user_id):
        cur_user = UserProfile.objects.get(id=int(user_id))
        curuser_ate_food = UserHaveAte.objects.filter(user=cur_user)
        user_atefood_list = []
        for ate_food in curuser_ate_food:
            user_ate_food = Food.objects.get(id=ate_food.food_id)
            user_atefood_list.append(user_ate_food)

        return render(request, "user/user_haveeated.html", {
            'user':cur_user,
            'foods':user_atefood_list,
        })


# 用户想吃的食物的列表
class UserWantEatView(View):
    def get(self, request, user_id):
        cur_user = UserProfile.objects.get(id=int(user_id))
        curuser_want_food = UserWantEat.objects.filter(user=cur_user)
        user_wantfood_list = []
        for want_food in curuser_want_food:
            user_want_food = Food.objects.get(id=want_food.food_id)
            user_wantfood_list.append(user_want_food)
        return render(request, "user/user_wanteat.html", {
            'user':cur_user,
            'foods':user_wantfood_list,
        })


# 用户分享的信息
class UserShareView(View):
    def get(self, request, user_id):
        cur_user = UserProfile.objects.get(id=int(user_id))
        all_food = Food.objects.all()
        cur_user_foods = all_food.filter(user=cur_user)
        return render(request, "user/user_share.html", {
            'user':cur_user,
            'foods':cur_user_foods,
        })


# 用户关注其他用户的动作
class FollowView(LoginRequiredMixin, View):
    def post(self, request):
        cur_user = request.user
        user_id = int(request.POST.get('id', ''))
        action = request.POST.get('action', '')
        if user_id and action:
            user = UserProfile.objects.get(pk=user_id)
            if action == 'follow':
                cur_user.following.add(user)
                create_action(cur_user, FOLLOW, user)
            elif action == 'unfollow':
                cur_user.following.remove(user)
            else:
                return JsonResponse(JSON_FAIL(STATUS_INVALID_ARGUMENTS))
            return JsonResponse({'status':True})
        return JsonResponse(JSON_FAIL(STATUS_INVALID_ARGUMENTS), status=400)


# 获取当前用户所在的城市
class GetCityView(View):

apps/user/templates/user/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>链接失效</title>
</head>
<body>
<p>链接失效，请重新注册。</p>
</body>
</html>

apps/user/templates/user/navbar.html
{% load widget_tweaks %}
<div class="navbar">
    <div class="nav">
        <ul>
            <li>
                <a href="{% url 'index' %}">首页</a>
                <span class="cursor"></span>
            </li>
            <li>
                <a href="{% url 'topic:topiclist' %}">专题</a>
                <span class="cursor"></span>
            </li>
            <li>
                <a href="{% url 'food:foodexplore' %}">发现</a>
                <span class="cursor"></span>
            </li>
            <li>
                <a href="{% url 'food:foodlist' %}">好吃</a>
                <span class="cursor"></span>
            </li>
{#            <li>#}
{#                <a href="{% url 'forum:index' %}">讨论区</a>#}
{#                <span class="cursor"></span>#}
{#            </li>#}
        </ul>
        {% if request.user.is_authenticated %}
            <a href="{% url 'food:foodcreate' %}"><button type="button">分享</button></a>
            <a href="{% url 'topic:topiccreate' %}"><button type="button">创建</button></a>
            <div class="user-name">
                <button type="button" name="user-name-btn" class="user-name-btn">{{ request.user.username }}
                    <span class="redpoint" style="display: none;"></span>
                </button>
                <ul class="user-dropdown">
                    <a href="{% url 'user:userindex' user.id %}"><li>资料</li></a>
                    <a id="message">
                        <li>私信 (<span id="msg-count">0</span>)</li>
                    </a>
                </ul>
            </div>
        {% else %}
            <a href="{% url 'user:login' %}"><button type="button" name="login" id="login-btn">登录</button></a>
            <a href="{% url 'user:register' %}"><button type="button" name="register" id="register-btn">注册</button></a>
        {% endif %}
{#        <form method="post" action="{% url 'search:search' %}">#}
{#            {% csrf_token %}#}
{#            {{ search_form.q | attr:"id:search" | attr:"placeholder:寻觅好吃……"}}#}
{#        </form>#}
    </div>
</div>

apps/user/templates/user/register.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <meta charset="utf-8">
        <title>注册</title>
        <style media="screen">
            .user-container {
                margin-top: -250px !important;
            }
        </style>
        <link href="{% static 'css/vendors.css' %}" rel="stylesheet">
        <link href="{% static 'css/user_register.css' %}" rel="stylesheet">
        <script type="text/javascript" src="{% static 'js/vendors.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/user_register.js' %}"></script></head>
    <body>
        <div class="navbar">
            
            <div class="nav">
                <ul>
                    <a href="#">
                        <li>首页<span class="cursor"></span></li>
                    </a>
                    <a href="#">
                        <li>专题<span class="cursor"></span></li>
                    </a>
                    <a href="#">
                        <li>发现<span class="cursor"></span></li>
                    </a>
                    <a href="#">
                        <li>好吃<span class="cursor"></span></li>
                    </a>
                </ul>
                <a href="{% url 'user:login' %}"><button type="button" name="login" id="login-btn">登录</button></a>
                <a href="{% url 'user:register'  %}"><button type="button" name="register" id="register-btn">注册</button></a>
                <input type="text" name="search" value="寻找好物……" id="search">
            </div>
        </div>
        <div class="user-container">
            <div class="user-container-title">
                <h2>注册</h2>
                <h3>注册，加入我们的大家庭</h3>
            </div>
            <div class="form-container" id="form-container">
                <form class="" action="" method="post" autocomplete="off">
                    <div class="form-item">
                        <label for="username"></label>
                        <input type="username" name="username" id="username" placeholder="请输入您的注册用户名">
                    </div>
                    <div class="form-item">
                        <label for="email"></label>
                        <input type="email" name="email" id="email" placeholder="请输入您的注册邮箱">
                    </div>
                    <div class="form-item">
                        <label for="password"></label>
                        <input type="password" name="password" id="password" placeholder="请输入密码">
                    </div>
                    <div class="form-item">
                        <label for="confirmPassword"></label>
                        <input type="password" name="confirmPassword" id="confirmPassword" placeholder="请再次输入密码">
                    </div>
{#                    <div class="form-item">#}
{#                        <label for="captch"></label>#}
{#                    </div>#}
{#                    {{ register_form.captcha }}#}

                    <div class="form-item">
                        <input type="submit" name="register" id="register-btn" value="注册">
                    </div>
                    <div class="register-tab">
                        <a href="{% url 'user:login' %}">已有账号</a>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </body>
</html>

apps/user/templates/user/user_base.html
{% load staticfiles %}
{% load thumbnail %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'font/font-awesome-4.5.0/css/font-awesome.min.css' %}" media="screen" title="no title" charset="utf-8">
        <link href="{% static 'css/vendors.css' %}" rel="stylesheet">
        <link href="{% static 'css/user_base.css' %}" rel="stylesheet">
    {% block custom_css %}{% endblock %}
        <title>{% block custom_head %}{% endblock %}</title>
    </head>

    <body>
        {% include 'user/navbar.html' %}
        <div class="user-container clearfix">
            {% with following_num=user.following.count followers_num=user.followers.count %}
            <div class="user-main clearfix">

                {% if user.image %}
{#                <div class="user-portrait" style="background-image: url('{{ MEDIA_URL }}{{ user.image }}')">#}
                 <div class="user-portrait" style="">
                    <img width="100" height="100"  src = "{{ MEDIA_URL }}{{ user.image }}"/>
                {% else %}
                <div class="user-portrait">
                {% endif %}

                {% if user.id != request.user.id %}
                <a href="#">
                    {% if request.user in user.followers.all %}
                    <button type="button" data-id="{{ user.id }}" data-action="unfollow" id="follow-btn" name="button" class="follow-btn unfollow">取消关注</button>
                    {% else %}
                    <button type="button" data-id="{{ user.id }}" data-action="follow" id="follow-btn" name="button" class="follow-btn follow">关注</button>
                    {% endif %}
                </a>
                {% else %}
                    <a href="{% url 'user:logout' %}">
                    <button type="button" class="follow-btn" style="background-color:#DC143C;">退出登录</button>
                    </a>
                {% endif %}
                </div>

                <div class="user-info">
                    <h2 class="user-name"><i class="fa {% if user.gender == "f" %}fa-venus{% else %}fa-mars{% endif %}"></i>{{ user.username }}</h2>
                    <h4 class="user-area"><i class="fa fa-location-arrow" aria-hidden="true"></i> {{ user.location | default:"外星" }}</h4>
                    <h4 class="user-desc">{{ user.introduction | default:"这个人什么也没写" }}</h4>
                    {% if user.id != request.user.id %}
                    <span><button id="private">私信</button></span>
                    {% endif %}
                </div>
                <a href="{% url 'user:userfollower' user.id %}">
                    <div class="user-follower">
                        <div class="follow-num">{{ followers_num }}</div>
                        粉丝
                    </div>
                </a>
                <a href="{% url 'user:userfollowing' user.id %}">
                    <div class="user-following">
                        <div class="follow-num">{{ following_num }}</div>
                        关注
                    </div>
                </a>
            </div>
            {% endwith %}

            <div class="user-tabs clearfix">
                <a href="{% url 'user:userindex' user.id %}">
                    <div class="tab-item {% if request.TAB == "home" %}current-tab{% endif %}">
                        主页
                    </div>
                </a>
                <a href="{% url 'user:usershare' user.id %}">
                    <div class="tab-item {% if request.TAB == "share" %}current-tab{% endif %}">
                        分享
                    </div>
                </a>
                <a href="{% url 'user:topiccollection' user.id %}">
                    <div class="tab-item {% if request.TAB == "collection" %}current-tab{% endif %}">
                        专题收藏
                    </div>
                </a>
                <a href="{% url 'user:usereated' user.id %}">
                    <div class="tab-item {% if request.TAB == "ate" %}current-tab{% endif %}">
                        吃过的
                    </div>
                </a>
                <a href="{% url 'user:userwanteat' user.id %}">
                    <div class="tab-item {% if request.TAB == "wta" %}current-tab{% endif %}">
                        想吃的
                    </div>
                </a>
                <a href="{% url 'user:userfollowing' user.id %}">
                    <div class="tab-item {% if request.TAB == "following" %}current-tab{% endif %}">
                        关注
                    </div>
                </a>
                <a href="{% url 'user:userfollower' user.id %}">
                    <div class="tab-item {% if request.TAB == "followers" %}current-tab{% endif %}">
                        粉丝
                    </div>
                </a>
                {% if request.user.id == user.id %}
{#                <a href="{% url 'user:moments' %}">#}
{#                    <div class="tab-item {% if request.TAB == "moments" %}current-tab{% endif %}">#}
{#                        吃友圈#}
{#                    </div>#}
{#                </a>#}
                <a href="{% url 'user:usersetting' user.id %}">
                    <div class="tab-item  {% if request.TAB == "profile" %}current-tab{% endif %}">
                        编辑资料
                    </div>
                </a>
                {% endif %}
            </div>
            {% block content %}{% endblock %}

        </div>
    {% include 'user/chat.html' %}
    <script src="{% static 'js/vendors.js' %}"></script>
    <script src="{% static 'js/user_base.js' %}"></script>
    <script src="{% static 'js/js.cookie.js' %}"></script>
    <script src="http://apps.bdimg.com/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static 'js/csrf.js' %}"></script>
    <script src="{% static 'js/chat.js' %}"></script>
    <script type="text/javascript">
        $(function(){
            $("#private").click(function() {
                var userId = $("#follow-btn").attr('data-id');
                openChatBar(userId);
            });
            $("#follow-btn").click(function(event) {
                var that = $(this);
                var id = that.attr('data-id');
                var action = that.attr('data-action');

                $.ajax({
                    url: "{% url 'user:follow' %}",
                    method: "POST",
                    data: {
                        id: id,
                        action: action
                    }
                }).success(function(data) {
                    if(data.status == true) {
                        if (action == 'follow') {
                            that.attr('data-action', 'unfollow');
                            that.text('取消关注');
                        } else {
                            that.attr('data-action', 'follow');
                            that.text('关注');
                        }                     
                    }
                }).error(function(error) {
                    alert("网络异常");
                });
            });
        });
    </script>
{% block js %}{% endblock %}
</body>
</html>