apps/food/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-21 下午5:22'

from django.conf.urls import url


from .views import FoodCreateView, FoodDetailView, FoodExploreView, FoodListView

urlpatterns = [
    # 食物推荐发表
    url(r'^foodcreate/$', FoodCreateView.as_view(), name='foodcreate'),

    # 食物详情
    url(r'^fooddetail/(?P<food_id>\d+)/$', FoodDetailView.as_view(), name='fooddetail'),

    # 发现食物
    url(r'^foodexplore/$', FoodExploreView.as_view(), name='foodexplore'),

    # 食物列表
    url(r'^foodlist/$', FoodListView.as_view(), name='foodlist'),
]

apps/topic/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-21 下午4:52'
from django.conf.urls import url

from .views import TopicListView, TopicDetailView, TopicCreateView

urlpatterns = [
    # 话题列表
    url(r'^topiclist/$', TopicListView.as_view(), name='topiclist'),

    # 话题详情
    url(r'^topicdetail/(?P<topic_id>\d+)/$', TopicDetailView.as_view(), name='topicdetail'),

    # 创建话题
    url(r'^topiccreate/$', TopicCreateView.as_view(), name='topiccreate'),
]

chihuoapp/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from user.views import IndexView

from chihuoapp.settings import MEDIA_ROOT


urlpatterns = [

    # 后台管理页面url
    url(r'^admin/', admin.site.urls),

    # 首页URL配置
    url('^$', IndexView.as_view(), name="index"),

    # 用户相关的url
    url(r'^user/', include('user.urls', namespace="user")),

    # 帖子
    url(r'^forum/', include('forum.urls', namespace="forum")),

    # 专题
    url(r'^topic/', include('topic.urls', namespace="topic")),

    # 食物
    url(r'^food/', include('food.urls', namespace="food")),

    # 验证码部分
    url(r'^captcha/', include('captcha.urls')),

    # 处理静态文件的函数配置
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

    # ] + static('static/', document_root=settings.STATIC_ROOT) + static('media/', document_root=settings.MEDIA_ROOT)

apps/topic/models.py
from datetime import datetime

from django.db import models
from django.core.urlresolvers import reverse

from user.models import UserProfile
from food.models import Food
# Create your models here.


# 食物专题信息
class FoodTopic(models.Model):
    title = models.CharField(max_length=32, verbose_name='专题名称')
    cover_image = models.ImageField(upload_to='topic/cover/%Y/%m/%d', verbose_name='封面图片', default="image/foodtopic.jpg")
    description = models.TextField(verbose_name='专题描述')
    total_collects = models.PositiveIntegerField(db_index=True, default=0, verbose_name='收藏数')
    tags = models.CharField(max_length=64, default='', verbose_name='专题标签')
    food = models.ManyToManyField(Food, related_name='topics_belong', verbose_name='包含美食')
    user = models.ForeignKey(UserProfile, related_name='topics_shared', verbose_name='创建用户', blank=True, null=True)
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    def __str__(self):
        return self.title

    # # 获取专题详情的界面的URL地址
    # def get_absolute_url(self):
    #     return reverse('topic:topicdetail', kwargs={'topic_id':self.id})

    class Meta:
        verbose_name = "美食专题"
        verbose_name_plural = verbose_name

apps/topic/forms.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-7-11 下午1:08'

from django import forms
from .models import FoodTopic


# 创建一个专题的表单
class TopicForm(forms.ModelForm):
    class Meta:
        model = FoodTopic
        fields = ['title','cover_image','description', 'tags', 'food']

apps/topic/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.backends import ModelBackend
from django.db.models import Q
from django.views.generic.base import View
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse

from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from actions.utils import create_action
from constants import *

from .models import FoodTopic
from .forms import TopicForm
# from operation.models import FoodInTopic
from food.models import Food


# 话题列表
class TopicListView(View):
    def get(self, request):
        all_topics = FoodTopic.objects.all()

        # 对所有的专题进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1

        p = Paginator(all_topics, 6, request=request)
        topics = p.page(page)
        return render(request, "topic/topic_list.html", {
            'all_topics':all_topics,
            'topics':topics,
        })


# 话题详情
class TopicDetailView(View):
    def get(self, request, topic_id):
        cur_topic = FoodTopic.objects.get(id=int(topic_id))

        # cur_topic_food = cur_topic.foodintopic_set.all()
        # cur_topic_food = FoodInTopic.objects.filter(topic=cur_topic)
        # food_ids = [topic_food.food.id for topic_food in cur_topic_food]
        # all_topic_food = Food.objects.filter(id__in=food_ids)
        all_topic_food = cur_topic.food.all()



        return render(request, "topic/topic_detail.html", {
            'topic':cur_topic,
            # 'cur_topic_food': cur_topic_food,
            'all_topic_food':all_topic_food,
        })


# 创建新的专题
class TopicCreateView(View):
    def get(self, request):
        form = TopicForm()
        # categorys = FoodCategory.objects.all()
        foods = Food.objects.all()
        return render(request, "topic/topic_create.html", {
            'form':form,
            'foods':foods,
        })

    def post(self, request):
        form = TopicForm(request.POST, request.FILES)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.user = request.user
            topic.save()
            form.save_m2m()
            create_action(request.user, SHARE, topic)
            return HttpResponseRedirect(reverse('topic:topiclist'))
        else:
            # categorys = FoodCategory.objects.all()
            foods = Food.objects.all()
            return render(request, "topic/topic_create.html", {
                'form': form,
                'foods': foods,
            })

apps/topic/templates/topic/topic_create.html
{% extends 'food/base.html' %}
{% load thumbnail %}
{% load staticfiles %}
{% load widget_tweaks  %}
{% block custom_title %}
    专题创建
{% endblock %}
{% block custom_css %}
    <link href="{% static 'css/food_create.css' %}" rel="stylesheet">
    <style type="text/css">
    .errorlist {
        color: red;
    }
    </style>
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/food_create.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="create-container">
            <div class="title">
                创建专题
            </div>

            <form class="create-form" enctype="multipart/form-data" action="." method="post" enctype="multipart/form-data">
                <div class="form-item">
                    <label class="form-label">封面图片</label>
                    {{ form.cover_image.errors }}
                    <div class="preview-main clearfix">
                        <div class="preview-img" id="preview-img" style="background-image: url{% static 'images/topic3.jpg' %}"></div>
                        <label for="upload" class="upload">
                            + 上传图片
                        </label>
                        {{ form.cover_image | attr:"id:upload"}}
                    </div>
                </div>

                <div class="form-item">
                    <label class="form-label" for="create-title">标题</label>
                    {{ form.title.errors }}
                    <div class="item-input">
                        {{ form.title | add_class:"input" | attr:"placeholder:请输入标题"}}
                    </div>
                </div>

                <div class="form-item">
                    <label class="form-label" for="create-type">包含食物</label>
                    {{ form.category.errors }}
                    <div class="selections">
                       {{ form.food | add_class:"types" }}
                    </div>
                </div>
                <div class="form-item">
                    <label class="form-label" for="create-tag">标签</label>
                    {{ form.tags.errors }}
                    <div class="item-input">
                        {{ form.tags | add_class:"input" | attr:"placeholder:请输入标签，以逗号分隔" }}
                    </div>
                </div>

{#                <div class="form-item">#}
{#                    <label class="form-label" for="create-link">来源链接</label>#}
{#                    {{ form.link.errors }}#}
{#                    <div class="item-input">#}
{#                        <input type="url" name="link" class="input" id="create-link" placeholder="http://">#}
{#                    </div>#}
{#                </div>#}

                <div class="form-item">
                    <label class="form-label" for="create-desc">简介</label>
                    {{ form.description.errors }}
                    <div class="item-input">
                        {{ form.description | add_class:"textarea" | attr:"placeholder:请输入简介" }}
                    </div>
                </div>

                <div class="form-item btn-item">
                    <button type="submit" name="share" class="form-btn share-btn">分享</button>
                    <button type="reset" name="cancel" class="form-btn cancel-btn">重置</button>
                </div>
                {% csrf_token %}
            </form>

    </div>
{% endblock %}

apps/topic/templates/topic/topic_detail.html
{% extends 'food/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block custom_title %}
    专题详情
{% endblock %}
{% block custom_css %}
    <link href="{% static 'css/topic_detail.css' %}" rel="stylesheet">
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/topic_detail.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="details-container">
            <div class="topic-content">
                <img width="1048" height="350" src="{{ MEDIA_URL }}{{ topic.cover_image }}"/>
                <div class="topic-info">
                    <h1 class="topic-title">{{ topic.title }}</h1>
                    <button type="button" name="button" id="collect" data-id="" data-action="">收藏专题</button>
                    <div class="topic-desc">
                        {{ topic.description }}
                    </div>
                </div>
            </div>
            {% for food in all_topic_food %}
            <div class="detail-item">
                <a href="{% url 'food:fooddetail' food.id %}">
                    <div class="detail-img-left" style="">
                        <img width="250" height="150" src="{{ MEDIA_URL }}{{ food.cover_image }}"/>
                    </div>
                </a>
                <div class="detail-content">
                    <h2 class="detail-title">
                        <a href="{% url 'food:fooddetail' food.id %}">{{ food.title }}</a>
                    </h2>

                    <div class="detail-desc-wrapper">
                        <p class="detail-desc">
                            {{ food.description }}
                        </p>
                    </div>

                    <div class="detail-bottom">
                        <div class="detail-tags">
                            <span class="tags-tip">标签：</span>
                            {% for tag in food.get_tags_list %}
                                <i class="tag">{{ tag }}</i>
                            {% endfor %}

                            <div class="like">
                                <span class="like-count">{{ food.total_likenum }}</span>
                                <i class="fa fa-heart"></i>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
{% endblock %}
{% block custom_script %}
    <script type="text/javascript">

            (function() {
                var collectDom = $("collect");

                collectDom.click(function(event) {
                    var self = this;
                    var id = $getDataOf(this, "id");
                    var action = $getDataOf(this, "action");

                    $ajax({
                        url: "",
                        method: "POST",
                        data: {

                        }
                    }).then(function(data) {
                        self.innerHTML = "已收藏";
                        self.className = "collected";
                    }).catch(function(error) {
                        alert("网络异常");
                    });
                });
            })();
        </script>
{% endblock %}

apps/topic/templates/topic/topic_list.html
{% extends 'food/base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block custom_title %}
    专题列表
{% endblock %}
{% block custom_css %}
    <link href="{% static 'css/topic_list.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/topic_list.js' %}"></script>
{% endblock %}
{% block content %}
    <div class="topic-container">

            <div class="topic-container-main">
                {% for topic in topics.object_list %}

                <div class="topic-item">

                    <a href="{% url 'topic:topicdetail' topic.id %}">
{#                        {% thumbnail topic.cover_image "393x188" crop="center" as im %}#}
{#                             <div class="topic-item-img" style="background-image: url('{{ im.url }}')"></div>#}
{#                        {% endthumbnail %}#}
                        <div class="topic-item-img" style="">
                            <img width="393" height="188"  src="{{ MEDIA_URL }}{{ topic.cover_image }}">
                        </div>
                    </a>
                    <div class="topic-item-desc">
                        <a href="{% url 'topic:topicdetail' topic.id %}"><h3 class="desc-title">{{ topic.title }}</h3></a>
                        <a href="{% url 'topic:topicdetail' topic.id %}"><h4 class="desc-content">{{ topic.description }}</h4></a>
                    </div>
                    <div class="topic-item-info">

                        <i class="fa fa-heart"><span class="num">{{ topic.total_collects }}</span></i>
                        <i class="fa fa-comments"><span class="num">97</span></i>
                        <a href="#"><a href="#"><i class="fa fa-share-alt"></i></a></a>
                    </div>
                </div>

                {% endfor %}
            </div>
        </div>
{% endblock %}
{% block custom_script %}{% endblock %}