apps/food/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-21 下午5:22'

from django.conf.urls import url


from .views import FoodCreateView, FoodDetailView, FoodExploreView, FoodListView

urlpatterns = [
    # 食物推荐发表
    url(r'^foodcreate/$', FoodCreateView.as_view(), name='foodcreate'),

    # 食物详情
    url(r'^fooddetail/(?P<food_id>\d+)/$', FoodDetailView.as_view(), name='fooddetail'),

    # 发现食物
    url(r'^foodexplore/$', FoodExploreView.as_view(), name='foodexplore'),

    # 食物列表
    url(r'^foodlist/$', FoodListView.as_view(), name='foodlist'),
]

apps/topic/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-21 下午4:52'
from django.conf.urls import url

from .views import TopicListView, TopicDetailView, TopicCreateView

urlpatterns = [
    # 话题列表
    url(r'^topiclist/$', TopicListView.as_view(), name='topiclist'),

    # 话题详情
    url(r'^topicdetail/(?P<topic_id>\d+)/$', TopicDetailView.as_view(), name='topicdetail'),

    # 创建话题
    url(r'^topiccreate/$', TopicCreateView.as_view(), name='topiccreate'),
]

apps/user/urls.py
# -*- coding: utf-8 -*-
__author__ = 'Dee'
__date__ = '17-6-19 上午10:25'
from django.conf.urls import url

from .views import LoginView, RegisterView, ActiveView, LogoutView, UserFollowingView, UserShareView
from .views import TopicCollectionView, UserIndexView, UserSettingView, UserHaveEatedView, UserFollowerView, UserWantEatView
from .views import FollowView, GetCityView

urlpatterns = [
    # 账户相关
    # 用户登录页面
    url(r'^login/$', LoginView.as_view(), name='login'),
    # 用户登出页面
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    # 用户注册页面
    url(r'^register/$', RegisterView.as_view(), name="register"),
    # 用户激活页面
    url(r'^active_user/(?P<active_code>.*)/$', ActiveView.as_view(), name="active_user"),


    #用户个人信息相关
    # 当前用户在关注谁
    url(r'^userfollowing/(?P<user_id>\d+)/$', UserFollowingView.as_view(), name="userfollowing"),
    # 当前用户的粉丝
    url(r'^userfollower/(?P<user_id>\d+)/$', UserFollowerView.as_view(), name="userfollower"),
    # 用户收藏的专题
    url(r'^topiccollection/(?P<user_id>\d+)/$', TopicCollectionView.as_view(), name='topiccollection'),
    # 用户首页
    url(r'^userindex/(?P<user_id>\d+)/$', UserIndexView.as_view(), name='userindex'),
    # 用户设置,包括用户的个人信息设置和用户的背景图片的设置
    url(r'^usersetting/(?P<user_id>\d+)/$', UserSettingView.as_view(), name='usersetting'),
    # 用户吃过的食物列表
    url(r'^usereated/(?P<user_id>\d+)/$', UserHaveEatedView.as_view(), name='usereated'),
    # 用户想吃的食物列表
    url(r'^userwanteat/(?P<user_id>\d+)/$', UserWantEatView.as_view(), name='userwanteat'),
    # 用户分享的列表
    url(r'^usershare/(?P<user_id>\d+)/$', UserShareView.as_view(), name='usershare'),


    # 用户行为相关
    # 用户关注的动作
    url(r'^follow/$', FollowView.as_view(), name='follow'),
    # 根据省份获取城市
    url(r'^get_cities/$', GetCityView.as_view(), name='get_cities'),
]

chihuoapp/urls.py
from django.conf import settings
from django.conf.urls import url, include, handler404, handler500
from django.conf.urls.static import static
from django.contrib import admin
from django.views.static import serve

from user.views import IndexView

from chihuoapp.settings import MEDIA_ROOT


urlpatterns = [

    # 后台管理页面url
    url(r'^admin/', admin.site.urls),

    # 首页URL配置
    url('^$', IndexView.as_view(), name="index"),

    # 用户相关的url
    url(r'^user/', include('user.urls', namespace="user")),

    # 帖子
    url(r'^forum/', include('forum.urls', namespace="forum")),

    # 专题
    url(r'^topic/', include('topic.urls', namespace="topic")),

    # 食物
    url(r'^food/', include('food.urls', namespace="food")),

    # 验证码部分
    url(r'^captcha/', include('captcha.urls')),

    # 处理静态文件的函数配置
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

    # ] + static('static/', document_root=settings.STATIC_ROOT) + static('media/', document_root=settings.MEDIA_ROOT)

templates/index.html
<!DOCTYPE html>
{% load staticfiles %}
{% load thumbnail %}
<html>
    <head>
        <title>首页</title>
        <script src="http://localhost:8000/webpack-dev-server.js"></script>
        <link rel="stylesheet" href="{% static 'font/font-awesome-4.5.0/css/font-awesome.min.css' %}" media="screen" title="no title" charset="utf-8">
        <link rel="stylesheet" href="{% static 'css/vendors.css' %}">
        <link rel="stylesheet" href="{% static 'css/home_index.css' %}">

        <script type="text/javascript" src="{% static 'js/vendors.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/home_index.js' %}"></script>
    </head>
    <body>
       <div class="navbar">

            <div class="nav">
                <ul>
                    <a href="{% url 'index' %}">
                        <li>首页<span class="cursor"></span></li>
                    </a>
                    <a href="{% url 'topic:topiclist' %}">
                        <li>专题<span class="cursor"></span></li>
                    </a>
                    <a href="{% url 'food:foodexplore' %}">
                        <li>发现<span class="cursor"></span></li>
                    </a>
                    <a href="{% url 'food:foodlist' %}">
                        <li>好吃<span class="cursor"></span></li>
                    </a>
                </ul>
            {% if request.user.is_authenticated %}
                <a href="{% url 'user:login' %}">
                  <button type="button" name="button">分享</button>
                </a>
                <a href="{% url 'user:logout' %}">
                  <button type="button" name="button">登出</button>
                </a>
                <a href="{% url 'user:userindex' request.user.id %}" class="user-name">
                  <button type="button" name="user-name-btn" class="user-name-btn">{{ request.user.username }}</button>
                </a>
             {% else %}
                <a href="{% url 'user:login' %}"><button type="button" name="login" id="login-btn">登录</button></a>
                <a href="{% url 'user:register' %}"><button type="button" name="register" id="register-btn">注册</button></a>
             {% endif %}
{#                <input type="text" name="search" value="寻找好物……" id="search">#}
            </div>
        </div>
        <div class="container" id="container">
            <div class="container-top">
                <div class="desc">
                    <div class="desc-main">

                        发现，美食，分享
                    </div>
                </div>
                <div class="pineapple-logo">
                    Food Share
                </div>
            </div>
        </div>

        <div class="topic-container">
            <div class="topic-container-title">
                <h1><span class="title-hr"></span>精选专题<span class="title-hr"></span></h1>
            </div>
            <div class="topic-container-main">
                {% for topic in all_topics %}
                <div class="topic-item">

                    <a href="{% url 'topic:topicdetail' topic.id %}">
                        {% thumbnail topic.cover_image "1048x350" crop="center" as im %}
                            <div class="topic-item-img" style="background-image: url('{{ im.url }}')"></div>
                        {% endthumbnail %}
                    </a>
                    <div class="topic-item-desc">
                        <a href="{% url 'topic:topicdetail' topic.id %}"><h3 class="desc-title">{{ topic.title }}</h3></a>
                        <a href="{% url 'topic:topicdetail' topic.id %}"><h4 class="desc-content">{{ topic.description }}</h4></a>
                    </div>
                    <div class="topic-item-info">

                        <i class="fa fa-heart"><span class="num">{{ topic.total_collects }}</span></i>
                        <i class="fa fa-comments"><span class="num">97</span></i>
                        <a href="#"><a href="#"><i class="fa fa-share-alt"></i></a></a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </body>
</html>